import similarimg2 from "../../assets/category/similar-dj-img2.jfif";
import similarimg4 from "../../assets/category/similar-dj-img4.jpg";
import similarimg5 from "../../assets/category/similar-dj-img5.jpg";

export const productData = [
  {
    id: 1,
    title: "wedding  service",
    actualPrice: "₹30000",
    specialPrice: "₹20000",
    discount: "10% off",
    rating: "4 ★",
    reviews: 3000,
    brand: "Pioneer DJ",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg2,
    location: "BBSR",
  },
  {
    id: 2,
    title: "wedding dj service",
    actualPrice: "₹30000",
    specialPrice: "₹25000",
    discount: "10% off",
    rating: "3.8 ★",
    reviews: 3200,
    brand: "RANE",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg4,
    location: "BBSR",
  },
  {
    id: 3,
    title: "wedding dj service",
    actualPrice: "₹30000",
    specialPrice: "₹20000",
    discount: "10% off",
    rating: "4.1 ★",
    reviews: 4000,
    brand: "RANE",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg5,
    location: "Mumbai",
  },
  {
    id: 4,
    title: "wedding dj service",
    actualPrice: "₹40000",
    specialPrice: "₹35000",
    discount: "10% off",
    rating: "4.2 ★",
    reviews: 2000,
    brand: "Denon DJ",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg5,
    location: "new delhi",
  },
  {
    id: 5,
    title: "wedding dj service",
    actualPrice: "₹30000",
    specialPrice: "₹22000",
    discount: "10% off",
    rating: "4.8 ★",
    reviews: 2500,
    brand: "Denon DJ",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg5,
    location: "new delhi",
  },
  {
    id: 6,
    title: "wedding dj service",
    actualPrice: "₹50000",
    specialPrice: "₹30000",
    discount: "20% off",
    rating: "3.9 ★",
    reviews: 4500,
    brand: "Native Instruments",
    description: "Lorem ipsum dolor sit amet, consectetur...",
    image: similarimg5,
    location: "Mumbai",
  },
];
