import img1 from "../assets/service/sub-img1.avif";
import img2 from "../assets/service/sub-img2.webp";
import img3 from "../assets/service/sub-img3.jpg";
import img4 from "../assets/service/sub-img4.jpg";
import img5 from "../assets/service/sub-img5.jpg";

import image1 from "../assets/home/categoriesImages/dj.png";
import image2 from "../assets/home/categoriesImages/bass brand.png";
import image3 from "../assets/home/categoriesImages/tenthouse.png";
import image4 from "../assets/home/categoriesImages/wedding photographer.png";
import image5 from "../assets/home/categoriesImages/pandit.png";
export const CategoryData = [
  {
    id: "dj",
    title: "DJ Services",
    image: image1,
    tagline: "Beats That Breathe Fun",
    icon: "🎧",
    services: [
      {
        id: "dj-night",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
      {
        id: "wedding-dj",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
    ],
  },
  {
    id: "band",
    title: "Live Musical Band",
    image: image2,
    tagline: "Brass Beats the Best",
    icon: "🎺",
    services: [
      {
        id: "rock-band",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
    ],
  },
  {
    id: "photography",
    title: "Photography",
    image: image3,
    tagline: "Capture Every Moment",
    icon: "📸",
    services: [
      {
        id: "wedding-photography",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
    ],
  },
  {
    id: "catering",
    title: "Catering",
    image: image4,
    tagline: "Delicious Memories Served",
    icon: "🍽️",
    services: [
      {
        id: "veg-catering",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
    ],
  },
  {
    id: "decoration",
    title: "Decoration",
    image: image5,
    tagline: "Designs that Dazzle",
    icon: "🎉",
    services: [
      {
        id: "stage-decor",
        img: [img1, img2, img3, img4, img5],
        title: " Elegant Beats Wedding DJ Package",
        description: "Experience With All Cultures & Traditions",
        address: {
          country: "India",
          state: "Odisha",
          city: "Bhubaneswar",
          area: "patia",
          pincode: 123344,
        },
        vandor: "Aarav Mehta",
        rating: 4,
        reviews: 4000,
        price: "30,000",
        originalPrice: 80000,
        discountPercent: 50,
      },
    ],
  },
];

// const CategoryData = [
//   {
//     id: 1,
//     img: [img1, img2, img3, img4, img5],
//     title: " Elegant Beats Wedding DJ Package",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "Bhubaneswar",
//       area: "patia",
//       pincode: 123344,
//     },
//     vandor: "Aarav Mehta",
//     rating: 4,
//     reviews: 4000,
//     price: "30,000",
//     originalPrice: 80000,
//     discountPercent: 50,
//   },
//   {
//     id: 2,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "Bhubaneswar",
//       area: "patia",
//       pincode: 123344,
//     },
//     vandor: "Sowmya Raghavan",

//     rating: 4,
//     reviews: 4000,
//     price: 30000,
//     originalPrice: 80000,
//     discountPercent: 50,
//   },
//   {
//     id: 3,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Harpreet Kaur Sidhu",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 4,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Ananya Banerjee",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 5,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Rohan Patil",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 6,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Meenakshi Sharma",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 7,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Aarav Mehta",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 8,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Aarav Mehta",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
//   {
//     id: 9,
//     img: [img1, img2, img3, img4, img5],
//     title: "DJ Service",
//     description: "Experience With All Cultures & Traditions",
//     address: {
//       country: "India",
//       state: "Odisha",
//       city: "cuttack",
//       area: "barabati",
//       pincode: 123346,
//     },
//     vandor: "Aarav Mehta",

//     rating: 4,
//     reviews: 4000,
//     price: 40000,
//     originalPrice: 80000,
//     discountPercent: 40,
//   },
// ];

export default CategoryData;
